#!/bin/bash

set -e

DATA_DIR=${DATA_DIR:-/data}
SCAN_FREQUENCY=${SCAN_FREQUENCY:-1h}
OPTS=( "--max-workers=${MAX_WORKERS:-1}" )

if [ -n "$PROMETHEUS_URL" ]; then
    OPTS+=( "--prometheus-url=${PROMETHEUS_URL}" )
fi

function cleanup()
{
    {
        echo Shutting down
        pkill python3
        service nginx stop
    } | log
    exit 0
}

function log()
{
    sed -e "s/^/$(date): /"
}

{
    echo Scan frequency: $SCAN_FREQUENCY | log
    echo Max workers: $MAX_WORKERS | log
    echo Prometheus URL: ${PROMETHEUS_URL:-<auto-discovery>}
} | log

trap cleanup HUP INT

mkdir -p ${DATA_DIR}
nginx -t | log

while true; do
    if ! service nginx status &>/dev/null; then
        service nginx start | log
    fi

    echo Starting KRR | log
    python3 krr.py simple ${OPTS[@]} -f json \
        | sed -ne '/^{/,/^}/p' \
        | tr -d '\n' \
        | jq -r > $DATA_DIR/result.json

    python3 krr2prom.py <$DATA_DIR/result.json >$DATA_DIR/.result.prom

    mv $DATA_DIR/.result.prom $DATA_DIR/result.prom
    n=$(wc -l $DATA_DIR/result.prom)
    echo Generated $n metrics in $DATA_DIR/result.prom | log

    sleep $SCAN_FREQUENCY
done
