#!/bin/bash

set -e

function usage()
{
    echo "Usage: $0 [prometheus|prometheus-exporter port frequency] [krr-flags...]"
    echo '  prometheus                              Single-shot, print metrics to stdout.'
    echo '  prometheus-exporter port frequency      Server, exposes metrics on 0.0.0.0:$METRICS_PORT/metrics.'
}

export EXEC_MODE="$1"
shift || true
echo "Exec Mode: $EXEC_MODE"

case "$EXEC_MODE" in
    prometheus) : ;;
    prometheus-exporter)
        if [ $# -lt 2 ]; then
            usage
            exit 1
        fi

        export METRICS_PORT=$1
        export SCAN_FREQUENCY=$2
        shift 2
        echo Metrics port: $METRICS_PORT
        echo Scan frequency: $SCAN_FREQUENCY
    ;;
    *)
        usage
        exit 1
esac

set -x
exec python3 formatter-${EXEC_MODE}.py simple --formatter $EXEC_MODE "${@}"
